services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 28122003
      MYSQL_DATABASE: kindergarten
    ports:
      - 3306:3306
    networks:
      springboot-mysql-net:
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  kindergarten:
    container_name: kindergarten
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=kindergarten
      - MYSQL_USER=root
      - MYSQL_PASSWORD=28122003
    volumes:
      - /opt/app/bin:/app/bin
      - /opt/app/uploads:/app/uploads
    networks:
      springboot-mysql-net:
networks:
  springboot-mysql-net:
